kuaida/kda

app.js, components/publish.js, package.json, public/stylesheets/jindingwen/quill.bubble.css, public/stylesheets/jindingwen/quill.core.css, public/stylesheets/jindingwen/quill.snow.css, routes/publish.js, views/publish.ejs, webpack.config.js
=> Add publish page

collections/index.js
=> Modified Mongodb file.

components/publish.js, routes/publish.js, views/publish.ejs
This is a small test, and also modify publish.ejs and publish.js
=> 发布页添加头和尾，修改悬赏按钮颜色

app.js, components/question/question.js, public/stylesheets/question.css, routes/question.js, views/question.ejs, webpack.config.js
=> Finish question

public/stylesheets/index.css, views/index.ejs
=> third commit

app.js, routes/login.js, views/login.ejs, views/reg.ejs
=> 注册登录实现后台交互

views/head.ejs
=> 修改了响应式的bug

views/head.ejs
=> 更改了几个链接,使其能够跳转,但不充分,后续补上

collections/index.js
=> modified collection's Schema

collections/index.js
=> modified collection's index.js

app.js, routes/search.js, views/foot.ejs, views/head.ejs, views/search.ejs
=> 增加了搜索功能,优化了头部和尾部

components/publish.js
=> 修改提问页面输入框尺寸

collections/index.js
修改：     collections/index.js
add new field: 获得奖金总量  totalReward  {type:'Number',default:0}
=> add default content and new field

collections/index.js
=> fixed  question's bug

collections/index.js
=> 修改排版格式,解决Promise问题

components/question/question.js, routes/question.js, views/question.ejs
=> Question page is finish

components/userinfo/index.js, routes/userinfo.js
修改 我的个人主页 提交修改信息问题
要提交的变更：
修改：     components/userinfo/index.js
修改：     routes/userinfo.js
=> 修改前后端数据交互问题

routes/index.js, views/index.ejs
=> All show data in index page.

components/publish.js, redis/index.js, routes/publish.js
已经将redis模块加入项目，并且开启了redis服务在后台运行
在提问页面对应的路由中添加了标签初始的过程
=> 添加redis模块 修改提问页面

redis/connect.js, redis/index.js, routes/publish.js
修改的文件:
redis/index.js
redis/connect.js
components/publish.js
routes/publish.js
=> 提交redis的基本构建，后续继续完善

public/sass/stylesheets/index.scss, public/stylesheets/index.css, views/index.ejs
=> 修改汉子长度，修改赏金图标

views/head.ejs
将头部加入了一个金额显示,将user改成了user.nickName
=> 将头部加入了一个金额显示

routes/userinfo.js
Fixed didn't update user information.
=> Fixed didn't update user information.

app.js, components/question/question.js, routes/api.js, routes/question.js, views/question.ejs
Add api file. Request data from api file.
=> Add api file

.gitignore, components/question/question.js, public/stylesheets/question.css, routes/question.js, views/question.ejs
=> fixed adoptbtn commitbtn

redis/index.js, routes/index.js, views/index.ejs
=> redis 请求数据

public/stylesheets/style.css, views/foot.ejs, views/head.ejs
将头部和尾部还有一个style修改了,删除了头部和尾部引用的过多项
=> 将头部和尾部还有一个style修改了,删除了头部和尾部引用的过多项

collections/index.js, components/question/question.js, public/stylesheets/question.css, routes/api.js, views/question.ejs
=> question page set type

public/sass/stylesheets/index.scss, routes/index.js, views/index.ejs
question and gold https console change
=> https console

public/sass/stylesheets/index.scss, views/index.ejs
=> bootstrap border margin

views/index.ejs
=> jQuery bootstrap cdn 调换

components/question/question.js, public/stylesheets/question.css, routes/api.js
1 fixed adopt
2 fixed commit comment
3 add question user
=> fixed question page bug

routes/api.js
Add saveQuestion getQuestionById saveAnswer
=> Update api file

public/stylesheets/style.css, views/foot.ejs, views/head.ejs, views/index.ejs, views/login.ejs, views/question.ejs, views/reg.ejs, views/search.ejs
=> head style

components/question/question.js, public/sass/stylesheets/index.scss, public/stylesheets/question.css, views/search.ejs, views/userinfo.ejs
=> optimziation bug page

public/sass/stylesheets/index.scss, views/head.ejs, views/index.ejs, views/search.ejs
=> 优化了用户，头，搜索框
